"""hall fix

Revision ID: c59adb6ba273
Revises: e8fda19f88fb
Create Date: 2025-04-03 18:18:52.853633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59adb6ba273'
down_revision: Union[str, None] = 'e8fda19f88fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'halls', ['hall_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'halls', type_='unique')
    # ### end Alembic commands ###
