"""Добавлен статус к Seat

Revision ID: e8fda19f88fb
Revises: 85eda8d32931
Create Date: 2025-03-31 13:40:43.089157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8fda19f88fb'
down_revision: Union[str, None] = '85eda8d32931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('status', sa.Boolean(), nullable=False, server_default=sa.text("FALSE")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seats', 'status')
    # ### end Alembic commands ###
