# Generated by Django 5.0.2 on 2025-03-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0002_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='paymentMethod',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
