# Generated by Django 5.0.2 on 2025-04-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0003_customer_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
