# Generated by Django 5.0.2 on 2025-04-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0004_remove_order_customer_order_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='choosen_store',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
